# Supabase local development config
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
default_schema = "public"
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325

[auth]
enabled = true
email.enable_signup = true
email.double_confirm_changes = true
email.enable_confirmations = true

[storage]
enabled = true
file_size_limit = 52428800

[realtime]
enabled = true
max_bytes_per_second = 1048576
